version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/zennvote-backend/deploy/zennvote-backend-v2/
permissions:
  - object: /home/ubuntu/zennvote-backend/deploy/zennvote-backend-v2
    pattern: "*.sh"
    mode: 777
    type:
      -file
hooks:
  BeforeInstall:
    - location: clear.sh
      timeout: 180
  AfterInstall:
    - location: deploy.sh
      timeout: 180